---
# <*******************
# 
# Copyright 2016 Juniper Networks, Inc. All rights reserved.
# Licensed under the Juniper Networks Script Software License (the "License").
# You may not use this script file except in compliance with the License, which is located at
# http://www.juniper.net/support/legal/scriptlicense/
# Unless required by applicable law or otherwise agreed to in writing by the parties, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# 
# *******************>
#task file for ansible-role-noob-qfx
- name: Creating NOOB config
  template: src=noob.j2 dest={{ tmp_dir }}/noob.conf

- name: Checking NETCONF connectivity
  wait_for: host={{ node.oob.re0_address }} port=22 timeout=10
  register: netconf_result
  ignore_errors: True

- name: "Upload Node MNG configuration using netconify by console if NETCONF FAIL"
  juniper_junos_config:
    user: root
    load: 'override'
    src: "{{ tmp_dir }}/noob.conf"
    commit: true
    logfile: "{{ log }}"
    comment: "Jenkins {{ build }}"
    mode: telnet
    host: "{{ node.console.re0.server }}"
    port: "{{ node.console.re0.port }}"
    timeout: 300
  register: response
  when: netconf_result is failed

- name: Checking NETCONF connectivity
  wait_for: host={{ node.oob.re0_address }} port=22 timeout=30
  when: netconf_result is failed

- name: "Upgrading Junos OS if necessary ... please be  patient"
  juniper_junos_software:
    user: "{{ netconf_user }}"
    passwd: "{{ netconf_passwd }}"
    reboot_pause: 10
    reboot: yes
    version: "{{ OS_version }}"
    local_package: "{{ OS_dir }}/{{ OS_package }}"
    logfile: "{{ log }}"
  when: OS_version|default(None) != None and OS_package|default(None) != None
