---
OS_package:
OS_version:
autonomous_system: 6
core_interfaces:
- desc: '*** to vqfx1 ***'
  int: em3
  ip: 10.30.136.2
  mask: 30
- desc: '*** to vqfx2 ***'
  int: em4
  ip: 10.30.146.2
  mask: 30
ip_interfaces:
- int: em5
  ip: 10.30.82.1
  mask: 24
loopback_interface:
  ip: 10.30.100.6
management_interface:
  int: em0
  ip: 100.123.15.3
  mask: 16
node:
  console:
    re0:
      port: 20028
      server: '{{ vm_host_address.stdout }}'
  oob:
    re0_address: '{{ management_interface.ip }}'
protocol_bgp:
- group: CLOS
  neighbors:
  - asn: 3
    name: 10.30.136.1
  - asn: 4
    name: 10.30.146.1
routing_options:
- destination: 100.123.0.1
  static: 0.0.0.0/0
