import unittest
from jnpr.toby.security.infra import nessus
import mock
from mock import patch
from mock import Mock
from mock import MagicMock

vurl = {0: {'SSH Server Type and Version Information': ['Service detection', 1], 'Nessus Scan Information': ['Settings', 1], 'Telnet Server Detection': ['Service detection', 1], 'SNMP Query System Information Disclosure': ['SNMP', 1], 'SNMP Request Network Interfaces Enumeration': ['SNMP', 1], 'Ethernet MAC Addresses': ['General', 1], 'Common Platform Enumeration (CPE)': ['General', 1], 'RPC Services Enumeration': ['Service detection', 6], 'Device Type': ['General', 1], 'SNMP Protocol Version Detection': ['SNMP', 1], 'FTP Server Detection': ['Service detection', 1], 'SSH Protocol Versions Supported': ['General', 1], 'Host Fully Qualified Domain Name (FQDN) Resolution': ['General', 1], 'RPC portmapper Service Detection': ['RPC', 1], 'Network Time Protocol (NTP) Server Detection': ['Service detection', 1], 'SSH Algorithms and Languages Supported': ['Misc.', 1], 'Traceroute Information': ['General', 1], 'RPC portmapper (TCP)': ['RPC', 1], 'Junos Version Detection': ['Junos Local Security Checks', 1], 'OS Identification': ['General', 1], 'Local Checks Not Enabled (info)': ['Settings', 1], 'Backported Security Patch Detection (SSH)': ['General', 1], 'Ethernet Card Manufacturer Detection': ['Misc.', 1], 'SNMP Supported Protocols Detection': ['SNMP', 1], 'No Credentials Provided': ['Settings', 1]}, 1: {'FTP Supports Cleartext Authentication': ['FTP', 1], 'SSH Server CBC Mode Ciphers Enabled': ['Misc.', 1], 'SSH Weak MAC Algorithms Enabled': ['Misc.', 1]}, 2: {"SNMP 'GETBULK' Reflection DDoS": ['SNMP', 1], 'Unencrypted Telnet Server': ['Misc.', 1], 'SNMP Agent Default Community Names': ['SNMP', 1], 'Network Time Protocol (NTP) Mode 6 Scanner': ['Misc.', 1], 'SSH Weak Algorithms Supported': ['Misc.', 1], 'Finger Service Remote Information Disclosure': ['Misc.', 1], 'SNMP Agent Default Community Name (public)': ['SNMP', 1]}}
vurl_neg = {0: {'Backported Security Patch Detection (SSH)': ['General', 1], 'RPC portmapper (TCP)': ['RPC', 1], 'Junos Version Detection': ['Junos Local Security Checks', 1], 'OS Identification': ['General', 1], 'SNMP Request Network Interfaces Enumeration': ['SNMP', 1], 'SSH Algorithms and Languages Supported': ['Misc.', 1], 'Ethernet Card Manufacturer Detection': ['Misc.', 1], 'SNMP Supported Protocols Detection': ['SNMP', 1], 'Local Checks Not Enabled (info)': ['Settings', 1], 'Nessus Scan Information': ['Settings', 1], 'SSH Protocol Versions Supported': ['General', 1], 'SNMP Protocol Version Detection': ['SNMP', 1], 'RPC portmapper Service Detection': ['RPC', 1], 'RPC Services Enumeration': ['Service detection', 6], 'Common Platform Enumeration (CPE)': ['General', 1], 'Device Type': ['General', 1], 'SSH Server Type and Version Information': ['Service detection', 1], 'Traceroute Information': ['General', 1], 'Ethernet MAC Addresses': ['General', 1], 'FTP Server Detection': ['Service detection', 1], 'SNMP Query System Information Disclosure': ['SNMP', 1], 'Network Time Protocol (NTP) Server Detection': ['Service detection', 1], 'Host Fully Qualified Domain Name (FQDN) Resolution': ['General', 1], 'Telnet Server Detection': ['Service detection', 1], 'No Credentials Provided': ['Settings', 1]}, 1: {'FTP Supports Cleartext Authentication': ['FTP', 1], 'SSH Weak MAC Algorithms Enabled': ['Misc.', 1], 'SSH Server CBC Mode Ciphers Enabled': ['Misc.', 1]}, 2: {'Finger Service Remote Information Disclosure': ['Misc.', 1], 'Unencrypted Telnet Server': ['Misc.', 1], "SNMP 'GETBULK' Reflection DDoS": ['SNMP', 1], 'Network Time Protocol (NTP) Mode 6 Scanner': ['Misc.', 1], 'SSH Weak Algorithms Supported': ['Misc.', 1]}, 3: {'SNMP Agent Default Community Name (public)': ['SNMP', 1]}, 4: {'SNMP Agent Default Community Names': ['SNMP', 1]}}
full_scan = {'hosts': [
    {'scanprogresstotal': 100, 'numchecksconsidered': 100, 'score': 11560, 'critical': 1, 'progress': '100-100/200-200',
     'medium': 5, 'low': 3, 'asset_id': 2, 'scanprogresscurrent': 100, 'severity': 40, 'high': 1,
     'hostname': '10.207.147.168', 'host_id': 2, 'info': 30, 'host_index': 0, 'totalchecksconsidered': 100,
     'severitycount': {
         'item': [{'severitylevel': 0, 'count': 30}, {'severitylevel': 1, 'count': 3}, {'severitylevel': 2, 'count': 5},
                  {'severitylevel': 3, 'count': 1}, {'severitylevel': 4, 'count': 1}]}}], 'notes': [], 'filters': [
    {'name': 'host.id', 'group_name': 'vulnerability',
     'control': {'regex': '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}(,[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})*',
                 'readable_regex': '01234567-abcd-ef01-2345-6789abcdef01', 'type': 'entry'},
     'readable_name': 'Asset ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.bid', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*', 'readable_regex': 'NUMBER', 'type': 'entry'},
     'readable_name': 'Bugtraq ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_framework_canvas', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'CANVAS Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.canvas_package', 'group_name': 'vulnerability',
                                   'control': {'list': ['CANVAS', 'D2ExploitPack', 'White_Phosphorus'],
                                               'type': 'dropdown'}, 'readable_name': 'CANVAS Package',
                                   'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.xref:CERT-CC', 'group_name': 'vulnerability',
     'control': {'regex': '^CA-[0-9]+-[0-9]+(,CA-[0-9]+-[0-9]+)*$', 'readable_regex': 'CA-YYYY-ID (ie: CA-2003-08)',
                 'type': 'entry'}, 'readable_name': 'CERT Advisory ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:CERT', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$', 'readable_regex': 'Cert VU reference (ie: 10031)',
                 'type': 'entry'}, 'readable_name': 'CERT Vulnerability ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_framework_core', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'CORE Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.cpe', 'group_name': 'vulnerability',
                                   'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                   'readable_name': 'CPE', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.cve.raw', 'group_name': 'vulnerability',
     'control': {'regex': '^(CVE|CAN)-(1999|20[01][0-9])-[0-9]{4,}(,(CVE|CAN)-(1999|20[01][0-9])-[0-9]{4,})*$',
                 'readable_regex': 'CVE-2015-9876,CVE-2016-10456', 'type': 'entry'}, 'readable_name': 'CVE',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.cvss_base_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)?$', 'readable_regex': '7.5', 'type': 'entry'},
     'readable_name': 'CVSS Base Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss_temporal_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)$', 'readable_regex': '4.2', 'type': 'entry'},
     'readable_name': 'CVSS Temporal Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss_temporal_vector.raw', 'group_name': 'vulnerability', 'control': {
        'regex': '^CVSS2#E:(U|POC|F|H|ND)/RL:(OF|T|W|U|ND)/RC:(UC|UR|C|ND)(,(CVSS2#E:(U|POC|F|H|ND)/RL:(OF|T|W|U|ND)/RC:(UC|UR|C|ND)))*$',
        'readable_regex': 'E:H, E:F', 'type': 'entry'}, 'readable_name': 'CVSS Temporal Vector',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.cvss_vector.raw', 'group_name': 'vulnerability',
                                         'control': {
                                             'regex': '^CVSS2#AV:(L|A|N)/AC:(H|M|L)/Au:(N|S|M)/C:(N|P|C)/I:(N|P|C)/A:(N|P|C)(,(CVSS2#AV:(L|A|N)/AC:(H|M|L)/Au:(N|S|M)/C:(N|P|C)/I:(N|P|C)/A:(N|P|C)))*$',
                                             'readable_regex': 'AV:N, AV:A', 'type': 'entry'},
                                         'readable_name': 'CVSS Vector', 'operators': ['match', 'nmatch']},
    {'name': 'plugin.attributes.cvss3_base_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)?$', 'readable_regex': '7.5', 'type': 'entry'},
     'readable_name': 'CVSS v3.0 Base Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss3_temporal_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)$', 'readable_regex': '4.2', 'type': 'entry'},
     'readable_name': 'CVSS v3.0 Temporal Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss3_temporal_vector.raw', 'group_name': 'vulnerability', 'control': {
        'regex': '^CVSS:3.0/E:(U|P|F|H|X)/RL:(O|T|W|U|X)/RC:(C|U|R|X)(,(CVSS:3.0/E:(U|P|F|H|X)/RL:(O|T|W|U|X)/RC:(C|U|R|X)))*$',
        'readable_regex': 'E:H, E:F', 'type': 'entry'}, 'readable_name': 'CVSS v3.0 Temporal Vector',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.cvss3_vector.raw', 'group_name': 'vulnerability',
                                         'control': {
                                             'regex': '^CVSS:3.0/AV:(N|A|L|P)/AC:(L|H)/PR:(N|L|H)/UI:(N|R)/S:(U|C)/C:(H|L|N)/I:(H|L|N)/A:(H|L|N)(,(CVSS:3.0/AV:(N|A|L|P)/AC:(L|H)/PR:(N|L|H)/UI:(N|R)/S:(U|C)/C:(H|L|N)/I:(H|L|N)/A:(H|L|N)))*$',
                                             'readable_regex': 'AV:N, AV:A', 'type': 'entry'},
                                         'readable_name': 'CVSS v3.0 Vector', 'operators': ['match', 'nmatch']},
    {'name': 'plugin.attributes.xref:CWE', 'group_name': 'vulnerability',
     'control': {'regex': '^([0-9]+)(,[0-9]+)*$', 'readable_regex': 'CWE reference (ie: 200)', 'type': 'entry'},
     'readable_name': 'CWE', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'compliance_reference', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Compliance Reference',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.default_account', 'group_name': 'vulnerability',
                                         'control': {'list': ['true', 'false'], 'type': 'dropdown'},
                                         'readable_name': 'Default/Known Accounts', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.exploit_framework_d2_elliot', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Elliot Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.d2_elliot_name', 'group_name': 'vulnerability',
                                   'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                   'readable_name': 'Elliot Exploit Name',
                                   'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_available', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Exploit Available',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.xref:EDB-ID', 'group_name': 'vulnerability',
                                   'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$',
                                               'readable_regex': 'NUMBER', 'type': 'entry'},
                                   'readable_name': 'Exploit Database ID',
                                   'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_framework_exploithub', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'ExploitHub',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.exploitability_ease.raw', 'group_name': 'vulnerability',
                                   'control': {'list': ['Exploits are available', 'No exploit is required',
                                                        'No known exploits are available'], 'type': 'dropdown'},
                                   'readable_name': 'Exploitability Ease', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.exploited_by_malware', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Exploited By Malware',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.exploited_by_nessus', 'group_name': 'vulnerability',
                                   'control': {'list': ['true', 'false'], 'type': 'dropdown'},
                                   'readable_name': 'Exploited By Nessus', 'operators': ['eq', 'neq']},
    {'name': 'host.target', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': '192.168.1.2,172.16.2.1-172.16.2.100,10.100.5.0/24,host.example.com',
                 'type': 'entry'}, 'readable_name': 'Hostname/IP Address',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:IAVA', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+-[A-Za-z]-[0-9]+(,[0-9]+-[A-Za-z]-[0-9]+)*$',
                 'readable_regex': 'IAVA reference (ie: 2011-A-0151)', 'type': 'entry'}, 'readable_name': 'IAVA ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:IAVB', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+-[A-Za-z]-[0-9]+(,[0-9]+-[A-Za-z]-[0-9]+)*$',
                 'readable_regex': 'IAVB reference (ie: 2011-B-0151)', 'type': 'entry'}, 'readable_name': 'IAVB ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.stig_severity', 'group_name': 'vulnerability',
     'control': {'regex': '^[ivIV]+', 'readable_regex': 'IAVM Severity (ie: IV)', 'type': 'entry'},
     'readable_name': 'IAVM Severity', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:IAVT', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+-[A-Za-z]-[0-9]+(,[0-9]+-[A-Za-z]-[0-9]+)*$',
                 'readable_regex': 'IAVT reference (ie: 2011-A-0151)', 'type': 'entry'}, 'readable_name': 'IAVT ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.in_the_news', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'In The News',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.malware', 'group_name': 'vulnerability',
                                   'control': {'list': ['true', 'false'], 'type': 'dropdown'},
                                   'readable_name': 'Malware', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.exploit_framework_metasploit', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Metasploit Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.metasploit_name', 'group_name': 'vulnerability',
                                   'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                   'readable_name': 'Metasploit Name', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:MSFT', 'group_name': 'vulnerability',
     'control': {'regex': '^MS[0-9]+-[0-9]+(,MS[0-9]+-[0-9]+)*$', 'readable_regex': 'MS99-999,MS00-789',
                 'type': 'entry'}, 'readable_name': 'Microsoft Bulletin',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:OSVDB', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$', 'readable_regex': 'NUMBER', 'type': 'entry'},
     'readable_name': 'OSVDB ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.patch_publication_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Patch Publication Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.attributes.description', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Plugin Description',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.family_id', 'group_name': 'vulnerability', 'control': {
        'list': [{'id': 1, 'name': 'Red Hat Local Security Checks'}, {'id': 2, 'name': 'HP-UX Local Security Checks'},
                 {'id': 3, 'name': 'Debian Local Security Checks'}, {'id': 4, 'name': 'Solaris Local Security Checks'},
                 {'id': 5, 'name': 'Fedora Local Security Checks'}, {'id': 6, 'name': 'CGI abuses'},
                 {'id': 7, 'name': 'Gentoo Local Security Checks'}, {'id': 8, 'name': 'SuSE Local Security Checks'},
                 {'id': 9, 'name': 'AIX Local Security Checks'}, {'id': 10, 'name': 'Windows : Microsoft Bulletins'},
                 {'id': 11, 'name': 'Web Servers'}, {'id': 12, 'name': 'SMTP problems'},
                 {'id': 13, 'name': 'FreeBSD Local Security Checks'},
                 {'id': 14, 'name': 'Ubuntu Local Security Checks'},
                 {'id': 15, 'name': 'Slackware Local Security Checks'},
                 {'id': 16, 'name': 'Mandrake Local Security Checks'}, {'id': 17, 'name': 'Remote file access'},
                 {'id': 18, 'name': 'CentOS Local Security Checks'}, {'id': 19, 'name': 'FTP'},
                 {'id': 20, 'name': 'Windows'}, {'id': 21, 'name': 'MacOS X Local Security Checks'},
                 {'id': 22, 'name': 'Denial of Service'}, {'id': 23, 'name': 'Misc.'},
                 {'id': 24, 'name': 'Service detection'}, {'id': 25, 'name': 'Default Unix Accounts'},
                 {'id': 26, 'name': 'CGI abuses : XSS'}, {'id': 27, 'name': 'Gain root remotely'},
                 {'id': 28, 'name': 'RPC'}, {'id': 29, 'name': 'Windows : User management'},
                 {'id': 30, 'name': 'General'}, {'id': 31, 'name': 'Databases'},
                 {'id': 32, 'name': 'Peer-To-Peer File Sharing'}, {'id': 33, 'name': 'CISCO'},
                 {'id': 34, 'name': 'Firewalls'}, {'id': 35, 'name': 'Backdoors'}, {'id': 36, 'name': 'SCADA'},
                 {'id': 37, 'name': 'DNS'}, {'id': 38, 'name': 'Useless services'},
                 {'id': 39, 'name': 'Policy Compliance'}, {'id': 40, 'name': 'Gain a shell remotely'},
                 {'id': 41, 'name': 'Settings'}, {'id': 42, 'name': 'Port scanners'}, {'id': 43, 'name': 'Netware'},
                 {'id': 44, 'name': 'Finger abuses'}, {'id': 45, 'name': 'SNMP'}, {'id': 46, 'name': 'NIS'},
                 {'id': 47, 'name': 'Mandriva Local Security Checks'},
                 {'id': 48, 'name': 'VMware ESX Local Security Checks'}, {'id': 49, 'name': 'Brute force attacks'},
                 {'id': 50, 'name': 'Junos Local Security Checks'},
                 {'id': 51, 'name': 'Scientific Linux Local Security Checks'}, {'id': 52, 'name': 'Mobile Devices'},
                 {'id': 53, 'name': 'Oracle Linux Local Security Checks'},
                 {'id': 54, 'name': 'Amazon Linux Local Security Checks'},
                 {'id': 55, 'name': 'Palo Alto Local Security Checks'},
                 {'id': 56, 'name': 'Huawei Local Security Checks'},
                 {'id': 57, 'name': 'F5 Networks Local Security Checks'},
                 {'id': 58, 'name': 'OracleVM Local Security Checks'}, {'id': 59, 'name': 'Incident Response'},
                 {'id': 60, 'name': 'Virtuozzo Local Security Checks'}], 'type': 'dropdown_multi'},
                                         'readable_name': 'Plugin Family', 'operators': ['eq', 'neq']},
    {'name': 'plugin.id', 'group_name': 'vulnerability', 'control': {'maxlength': 1000,
                                                                     'regex': '^(0|[1-9][0-9]{0,6})(-([1-9][0-9]{0,6}))?(,(0|[1-9][0-9]{0,6})(-([1-9][0-9]{0,6}))?)*$',
                                                                     'readable_regex': 'XXXXX,XXXXX-XXXXX',
                                                                     'type': 'entry'}, 'readable_name': 'Plugin ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.plugin_modification_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Plugin Modification Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.name', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Plugin Name',
     'operators': ['eq', 'neq', 'match', 'nmatch']}, {'name': 'output', 'group_name': 'vulnerability',
                                                      'control': {'regex': '.*', 'readable_regex': 'text,other text',
                                                                  'type': 'entry'}, 'readable_name': 'Plugin Output',
                                                      'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.plugin_publication_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Plugin Publication Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.attributes.plugin_type', 'group_name': 'vulnerability',
     'control': {'list': ['local', 'remote'], 'type': 'dropdown'}, 'readable_name': 'Plugin Type',
     'operators': ['eq', 'neq']}, {'name': 'port.port', 'group_name': 'vulnerability', 'control': {'maxlength': 1000,
                                                                                                   'regex': '^[0-9]{1,5}(-[0-9]{1,5})?(,[0-9]{1,5}(-[0-9]{1,5})?)*$',
                                                                                                   'readable_regex': '80,8000-8080',
                                                                                                   'type': 'entry'},
                                   'readable_name': 'Port', 'operators': ['eq', 'neq', 'gte', 'lte']},
    {'name': 'port.protocol', 'group_name': 'vulnerability',
     'control': {'list': ['tcp', 'udp', 'icmp'], 'type': 'dropdown'}, 'readable_name': 'Protocol',
     'operators': ['eq', 'neq']}, {'name': 'modification', 'group_name': 'vulnerability',
                                   'control': {'list': ['Accepted', 'Recasted'], 'type': 'dropdown'},
                                   'readable_name': 'Recast & Accept', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.xref:Secunia', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$', 'readable_regex': 'NUMBER', 'type': 'entry'},
     'readable_name': 'Secunia ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.see_also', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'See Also',
     'operators': ['eq', 'neq', 'match', 'nmatch']}, {'name': 'severity', 'group_name': 'vulnerability',
                                                      'control': {'list': ['Info', 'Low', 'Medium', 'High', 'Critical'],
                                                                  'type': 'dropdown_multi'},
                                                      'readable_name': 'Severity', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.solution', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Solution',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.synopsis', 'group_name': 'vulnerability',
                                         'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                         'readable_name': 'Synopsis', 'operators': ['match', 'nmatch']},
    {'name': 'plugin.attributes.unsupported_by_vendor', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Unsupported By Vendor',
     'operators': ['eq', 'neq']}, {'name': 'tracking.first_found', 'group_name': 'vulnerability',
                                   'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD',
                                               'type': 'datefield'}, 'readable_name': 'Vulnerability First Seen',
                                   'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'tracking.last_found', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Vulnerability Last Seen',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.attributes.vuln_publication_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Vulnerability Publication Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'tracking.state', 'group_name': 'vulnerability',
     'control': {'list': ['New', 'Fixed', 'Active', 'Resurfaced'], 'type': 'dropdown'},
     'readable_name': 'Vulnerability State', 'operators': ['eq', 'neq']}], 'compliance': [], 'comphosts': [],
        'history': [
            {'uuid': '58c59ba0-22a4-48fb-b602-d50be9ef12ee', 'scheduler': 0, 'creation_date': 1540792945, 'owner_id': 2,
             'type': 'remote', 'status': 'completed', 'alt_targets_used': False, 'last_modification_date': 1540793587,
             'history_id': 11423531}],
        'info': {'timestamp': 1540793587, 'control': True, 'hostcount': 1, 'alt_targets_used': False,
                 'status': 'completed', 'edit_allowed': False, 'user_permissions': 128, 'object_id': 330,
                 'scan_start': 1540792945, 'shared': None, 'no_target': False,
                 'uuid': '58c59ba0-22a4-48fb-b602-d50be9ef12ee', 'name': 'Test', 'scanner_end': None,
                 'scanner_start': None, 'folder_id': None, 'owner': 'kkart@juniper.net', 'scan_type': 'remote',
                 'policy': 'Advanced Network Scan',
                 'schedule_uuid': 'template-e9c66add-fd51-688a-3329-420ef3f7d71ec780579ac958294b',
                 'hasaudittrail': True, 'haskb': True, 'targets': '10.207.147.168', 'acls': [
                {'id': None, 'display_name': None, 'name': None, 'permissions': 0, 'owner': None, 'type': 'default'},
                {'id': 2, 'display_name': 'kkart@juniper.net', 'name': 'kkart@juniper.net', 'permissions': 128,
                 'owner': 1, 'type': 'user'}], 'scanner_name': 'nessus-va-vm.englab.juniper.net',
                 'scan_end': 1540793587, 'pci-can-upload': False},
        'remediations': {'num_cves': 20, 'num_impacted_hosts': 0, 'num_remediated_cves': 0, 'remediations': [],
                         'num_hosts': 1}, 'vulnerabilities': [
        {'severity': 0, 'vuln_index': 1, 'plugin_id': 11111, 'count': 6, 'plugin_name': 'RPC Services Enumeration',
         'plugin_family': 'Service detection'}, {'severity': 2, 'vuln_index': 2, 'plugin_id': 10068, 'count': 1,
                                                 'plugin_name': 'Finger Service Remote Information Disclosure',
                                                 'plugin_family': 'Misc.'},
        {'severity': 0, 'vuln_index': 3, 'plugin_id': 10092, 'count': 1, 'plugin_name': 'FTP Server Detection',
         'plugin_family': 'Service detection'}, {'severity': 0, 'vuln_index': 4, 'plugin_id': 10223, 'count': 1,
                                                 'plugin_name': 'RPC portmapper Service Detection',
                                                 'plugin_family': 'RPC'},
        {'severity': 2, 'vuln_index': 5, 'plugin_id': 10264, 'count': 1,
         'plugin_name': 'SNMP Agent Default Community Names', 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 6, 'plugin_id': 10267, 'count': 1,
         'plugin_name': 'SSH Server Type and Version Information', 'plugin_family': 'Service detection'},
        {'severity': 0, 'vuln_index': 7, 'plugin_id': 10281, 'count': 1, 'plugin_name': 'Telnet Server Detection',
         'plugin_family': 'Service detection'},
        {'severity': 0, 'vuln_index': 8, 'plugin_id': 10287, 'count': 1, 'plugin_name': 'Traceroute Information',
         'plugin_family': 'General'}, {'severity': 0, 'vuln_index': 9, 'plugin_id': 10551, 'count': 1,
                                       'plugin_name': 'SNMP Request Network Interfaces Enumeration',
                                       'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 10, 'plugin_id': 10800, 'count': 1,
         'plugin_name': 'SNMP Query System Information Disclosure', 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 11, 'plugin_id': 10881, 'count': 1,
         'plugin_name': 'SSH Protocol Versions Supported', 'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 12, 'plugin_id': 10884, 'count': 1,
         'plugin_name': 'Network Time Protocol (NTP) Server Detection', 'plugin_family': 'Service detection'},
        {'severity': 0, 'vuln_index': 13, 'plugin_id': 11936, 'count': 1, 'plugin_name': 'OS Identification',
         'plugin_family': 'General'}, {'severity': 0, 'vuln_index': 14, 'plugin_id': 12053, 'count': 1,
                                       'plugin_name': 'Host Fully Qualified Domain Name (FQDN) Resolution',
                                       'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 15, 'plugin_id': 19506, 'count': 1, 'plugin_name': 'Nessus Scan Information',
         'plugin_family': 'Settings'}, {'severity': 1, 'vuln_index': 16, 'plugin_id': 34324, 'count': 1,
                                        'plugin_name': 'FTP Supports Cleartext Authentication', 'plugin_family': 'FTP'},
        {'severity': 0, 'vuln_index': 17, 'plugin_id': 35296, 'count': 1,
         'plugin_name': 'SNMP Protocol Version Detection', 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 18, 'plugin_id': 35716, 'count': 1,
         'plugin_name': 'Ethernet Card Manufacturer Detection', 'plugin_family': 'Misc.'},
        {'severity': 0, 'vuln_index': 19, 'plugin_id': 39520, 'count': 1,
         'plugin_name': 'Backported Security Patch Detection (SSH)', 'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 20, 'plugin_id': 40448, 'count': 1,
         'plugin_name': 'SNMP Supported Protocols Detection', 'plugin_family': 'SNMP'},
        {'severity': 2, 'vuln_index': 21, 'plugin_id': 41028, 'count': 1,
         'plugin_name': 'SNMP Agent Default Community Name (public)', 'plugin_family': 'SNMP'},
        {'severity': 2, 'vuln_index': 22, 'plugin_id': 42263, 'count': 1, 'plugin_name': 'Unencrypted Telnet Server',
         'plugin_family': 'Misc.'}, {'severity': 0, 'vuln_index': 23, 'plugin_id': 45590, 'count': 1,
                                     'plugin_name': 'Common Platform Enumeration (CPE)', 'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 24, 'plugin_id': 53335, 'count': 1, 'plugin_name': 'RPC portmapper (TCP)',
         'plugin_family': 'RPC'},
        {'severity': 0, 'vuln_index': 25, 'plugin_id': 54615, 'count': 1, 'plugin_name': 'Device Type',
         'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 26, 'plugin_id': 55932, 'count': 1, 'plugin_name': 'Junos Version Detection',
         'plugin_family': 'Junos Local Security Checks'},
        {'severity': 0, 'vuln_index': 27, 'plugin_id': 70657, 'count': 1,
         'plugin_name': 'SSH Algorithms and Languages Supported', 'plugin_family': 'Misc.'},
        {'severity': 1, 'vuln_index': 28, 'plugin_id': 70658, 'count': 1,
         'plugin_name': 'SSH Server CBC Mode Ciphers Enabled', 'plugin_family': 'Misc.'},
        {'severity': 1, 'vuln_index': 29, 'plugin_id': 71049, 'count': 1,
         'plugin_name': 'SSH Weak MAC Algorithms Enabled', 'plugin_family': 'Misc.'},
        {'severity': 2, 'vuln_index': 30, 'plugin_id': 76474, 'count': 1,
         'plugin_name': "SNMP 'GETBULK' Reflection DDoS", 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 31, 'plugin_id': 86420, 'count': 1, 'plugin_name': 'Ethernet MAC Addresses',
         'plugin_family': 'General'}, {'severity': 2, 'vuln_index': 32, 'plugin_id': 90317, 'count': 1,
                                       'plugin_name': 'SSH Weak Algorithms Supported', 'plugin_family': 'Misc.'},
        {'severity': 2, 'vuln_index': 33, 'plugin_id': 97861, 'count': 1,
         'plugin_name': 'Network Time Protocol (NTP) Mode 6 Scanner', 'plugin_family': 'Misc.'},
        {'severity': 0, 'vuln_index': 34, 'plugin_id': 110723, 'count': 1, 'plugin_name': 'No Credentials Provided',
         'plugin_family': 'Settings'}, {'severity': 0, 'vuln_index': 35, 'plugin_id': 117886, 'count': 1,
                                        'plugin_name': 'Local Checks Not Enabled (info)', 'plugin_family': 'Settings'}]}
full_scan_neg = {"error": "Unauthorized", 'hosts': [
    {'scanprogresstotal': 100, 'numchecksconsidered': 100, 'score': 11560, 'critical': 1, 'progress': '100-100/200-200',
     'medium': 5, 'low': 3, 'asset_id': 2, 'scanprogresscurrent': 100, 'severity': 40, 'high': 1,
     'hostname': '10.207.147.168', 'host_id': 2, 'info': 30, 'host_index': 0, 'totalchecksconsidered': 100,
     'severitycount': {
         'item': [{'severitylevel': 0, 'count': 30}, {'severitylevel': 1, 'count': 3}, {'severitylevel': 2, 'count': 5},
                  {'severitylevel': 3, 'count': 1}, {'severitylevel': 4, 'count': 1}]}}], 'notes': [], 'filters': [
    {'name': 'host.id', 'group_name': 'vulnerability',
     'control': {'regex': '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}(,[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})*',
                 'readable_regex': '01234567-abcd-ef01-2345-6789abcdef01', 'type': 'entry'},
     'readable_name': 'Asset ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.bid', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*', 'readable_regex': 'NUMBER', 'type': 'entry'},
     'readable_name': 'Bugtraq ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_framework_canvas', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'CANVAS Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.canvas_package', 'group_name': 'vulnerability',
                                   'control': {'list': ['CANVAS', 'D2ExploitPack', 'White_Phosphorus'],
                                               'type': 'dropdown'}, 'readable_name': 'CANVAS Package',
                                   'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.xref:CERT-CC', 'group_name': 'vulnerability',
     'control': {'regex': '^CA-[0-9]+-[0-9]+(,CA-[0-9]+-[0-9]+)*$', 'readable_regex': 'CA-YYYY-ID (ie: CA-2003-08)',
                 'type': 'entry'}, 'readable_name': 'CERT Advisory ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:CERT', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$', 'readable_regex': 'Cert VU reference (ie: 10031)',
                 'type': 'entry'}, 'readable_name': 'CERT Vulnerability ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_framework_core', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'CORE Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.cpe', 'group_name': 'vulnerability',
                                   'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                   'readable_name': 'CPE', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.cve.raw', 'group_name': 'vulnerability',
     'control': {'regex': '^(CVE|CAN)-(1999|20[01][0-9])-[0-9]{4,}(,(CVE|CAN)-(1999|20[01][0-9])-[0-9]{4,})*$',
                 'readable_regex': 'CVE-2015-9876,CVE-2016-10456', 'type': 'entry'}, 'readable_name': 'CVE',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.cvss_base_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)?$', 'readable_regex': '7.5', 'type': 'entry'},
     'readable_name': 'CVSS Base Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss_temporal_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)$', 'readable_regex': '4.2', 'type': 'entry'},
     'readable_name': 'CVSS Temporal Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss_temporal_vector.raw', 'group_name': 'vulnerability', 'control': {
        'regex': '^CVSS2#E:(U|POC|F|H|ND)/RL:(OF|T|W|U|ND)/RC:(UC|UR|C|ND)(,(CVSS2#E:(U|POC|F|H|ND)/RL:(OF|T|W|U|ND)/RC:(UC|UR|C|ND)))*$',
        'readable_regex': 'E:H, E:F', 'type': 'entry'}, 'readable_name': 'CVSS Temporal Vector',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.cvss_vector.raw', 'group_name': 'vulnerability',
                                         'control': {
                                             'regex': '^CVSS2#AV:(L|A|N)/AC:(H|M|L)/Au:(N|S|M)/C:(N|P|C)/I:(N|P|C)/A:(N|P|C)(,(CVSS2#AV:(L|A|N)/AC:(H|M|L)/Au:(N|S|M)/C:(N|P|C)/I:(N|P|C)/A:(N|P|C)))*$',
                                             'readable_regex': 'AV:N, AV:A', 'type': 'entry'},
                                         'readable_name': 'CVSS Vector', 'operators': ['match', 'nmatch']},
    {'name': 'plugin.attributes.cvss3_base_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)?$', 'readable_regex': '7.5', 'type': 'entry'},
     'readable_name': 'CVSS v3.0 Base Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss3_temporal_score', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+(\\.[0-9]+)$', 'readable_regex': '4.2', 'type': 'entry'},
     'readable_name': 'CVSS v3.0 Temporal Score', 'operators': ['lte', 'gte', 'eq', 'neq']},
    {'name': 'plugin.attributes.cvss3_temporal_vector.raw', 'group_name': 'vulnerability', 'control': {
        'regex': '^CVSS:3.0/E:(U|P|F|H|X)/RL:(O|T|W|U|X)/RC:(C|U|R|X)(,(CVSS:3.0/E:(U|P|F|H|X)/RL:(O|T|W|U|X)/RC:(C|U|R|X)))*$',
        'readable_regex': 'E:H, E:F', 'type': 'entry'}, 'readable_name': 'CVSS v3.0 Temporal Vector',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.cvss3_vector.raw', 'group_name': 'vulnerability',
                                         'control': {
                                             'regex': '^CVSS:3.0/AV:(N|A|L|P)/AC:(L|H)/PR:(N|L|H)/UI:(N|R)/S:(U|C)/C:(H|L|N)/I:(H|L|N)/A:(H|L|N)(,(CVSS:3.0/AV:(N|A|L|P)/AC:(L|H)/PR:(N|L|H)/UI:(N|R)/S:(U|C)/C:(H|L|N)/I:(H|L|N)/A:(H|L|N)))*$',
                                             'readable_regex': 'AV:N, AV:A', 'type': 'entry'},
                                         'readable_name': 'CVSS v3.0 Vector', 'operators': ['match', 'nmatch']},
    {'name': 'plugin.attributes.xref:CWE', 'group_name': 'vulnerability',
     'control': {'regex': '^([0-9]+)(,[0-9]+)*$', 'readable_regex': 'CWE reference (ie: 200)', 'type': 'entry'},
     'readable_name': 'CWE', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'compliance_reference', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Compliance Reference',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.default_account', 'group_name': 'vulnerability',
                                         'control': {'list': ['true', 'false'], 'type': 'dropdown'},
                                         'readable_name': 'Default/Known Accounts', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.exploit_framework_d2_elliot', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Elliot Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.d2_elliot_name', 'group_name': 'vulnerability',
                                   'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                   'readable_name': 'Elliot Exploit Name',
                                   'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_available', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Exploit Available',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.xref:EDB-ID', 'group_name': 'vulnerability',
                                   'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$',
                                               'readable_regex': 'NUMBER', 'type': 'entry'},
                                   'readable_name': 'Exploit Database ID',
                                   'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.exploit_framework_exploithub', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'ExploitHub',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.exploitability_ease.raw', 'group_name': 'vulnerability',
                                   'control': {'list': ['Exploits are available', 'No exploit is required',
                                                        'No known exploits are available'], 'type': 'dropdown'},
                                   'readable_name': 'Exploitability Ease', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.exploited_by_malware', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Exploited By Malware',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.exploited_by_nessus', 'group_name': 'vulnerability',
                                   'control': {'list': ['true', 'false'], 'type': 'dropdown'},
                                   'readable_name': 'Exploited By Nessus', 'operators': ['eq', 'neq']},
    {'name': 'host.target', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': '192.168.1.2,172.16.2.1-172.16.2.100,10.100.5.0/24,host.example.com',
                 'type': 'entry'}, 'readable_name': 'Hostname/IP Address',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:IAVA', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+-[A-Za-z]-[0-9]+(,[0-9]+-[A-Za-z]-[0-9]+)*$',
                 'readable_regex': 'IAVA reference (ie: 2011-A-0151)', 'type': 'entry'}, 'readable_name': 'IAVA ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:IAVB', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+-[A-Za-z]-[0-9]+(,[0-9]+-[A-Za-z]-[0-9]+)*$',
                 'readable_regex': 'IAVB reference (ie: 2011-B-0151)', 'type': 'entry'}, 'readable_name': 'IAVB ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.stig_severity', 'group_name': 'vulnerability',
     'control': {'regex': '^[ivIV]+', 'readable_regex': 'IAVM Severity (ie: IV)', 'type': 'entry'},
     'readable_name': 'IAVM Severity', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:IAVT', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]+-[A-Za-z]-[0-9]+(,[0-9]+-[A-Za-z]-[0-9]+)*$',
                 'readable_regex': 'IAVT reference (ie: 2011-A-0151)', 'type': 'entry'}, 'readable_name': 'IAVT ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.in_the_news', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'In The News',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.malware', 'group_name': 'vulnerability',
                                   'control': {'list': ['true', 'false'], 'type': 'dropdown'},
                                   'readable_name': 'Malware', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.exploit_framework_metasploit', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Metasploit Exploit Framework',
     'operators': ['eq', 'neq']}, {'name': 'plugin.attributes.metasploit_name', 'group_name': 'vulnerability',
                                   'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                   'readable_name': 'Metasploit Name', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:MSFT', 'group_name': 'vulnerability',
     'control': {'regex': '^MS[0-9]+-[0-9]+(,MS[0-9]+-[0-9]+)*$', 'readable_regex': 'MS99-999,MS00-789',
                 'type': 'entry'}, 'readable_name': 'Microsoft Bulletin',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.xref:OSVDB', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$', 'readable_regex': 'NUMBER', 'type': 'entry'},
     'readable_name': 'OSVDB ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.patch_publication_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Patch Publication Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.attributes.description', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Plugin Description',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.family_id', 'group_name': 'vulnerability', 'control': {
        'list': [{'id': 1, 'name': 'Red Hat Local Security Checks'}, {'id': 2, 'name': 'HP-UX Local Security Checks'},
                 {'id': 3, 'name': 'Debian Local Security Checks'}, {'id': 4, 'name': 'Solaris Local Security Checks'},
                 {'id': 5, 'name': 'Fedora Local Security Checks'}, {'id': 6, 'name': 'CGI abuses'},
                 {'id': 7, 'name': 'Gentoo Local Security Checks'}, {'id': 8, 'name': 'SuSE Local Security Checks'},
                 {'id': 9, 'name': 'AIX Local Security Checks'}, {'id': 10, 'name': 'Windows : Microsoft Bulletins'},
                 {'id': 11, 'name': 'Web Servers'}, {'id': 12, 'name': 'SMTP problems'},
                 {'id': 13, 'name': 'FreeBSD Local Security Checks'},
                 {'id': 14, 'name': 'Ubuntu Local Security Checks'},
                 {'id': 15, 'name': 'Slackware Local Security Checks'},
                 {'id': 16, 'name': 'Mandrake Local Security Checks'}, {'id': 17, 'name': 'Remote file access'},
                 {'id': 18, 'name': 'CentOS Local Security Checks'}, {'id': 19, 'name': 'FTP'},
                 {'id': 20, 'name': 'Windows'}, {'id': 21, 'name': 'MacOS X Local Security Checks'},
                 {'id': 22, 'name': 'Denial of Service'}, {'id': 23, 'name': 'Misc.'},
                 {'id': 24, 'name': 'Service detection'}, {'id': 25, 'name': 'Default Unix Accounts'},
                 {'id': 26, 'name': 'CGI abuses : XSS'}, {'id': 27, 'name': 'Gain root remotely'},
                 {'id': 28, 'name': 'RPC'}, {'id': 29, 'name': 'Windows : User management'},
                 {'id': 30, 'name': 'General'}, {'id': 31, 'name': 'Databases'},
                 {'id': 32, 'name': 'Peer-To-Peer File Sharing'}, {'id': 33, 'name': 'CISCO'},
                 {'id': 34, 'name': 'Firewalls'}, {'id': 35, 'name': 'Backdoors'}, {'id': 36, 'name': 'SCADA'},
                 {'id': 37, 'name': 'DNS'}, {'id': 38, 'name': 'Useless services'},
                 {'id': 39, 'name': 'Policy Compliance'}, {'id': 40, 'name': 'Gain a shell remotely'},
                 {'id': 41, 'name': 'Settings'}, {'id': 42, 'name': 'Port scanners'}, {'id': 43, 'name': 'Netware'},
                 {'id': 44, 'name': 'Finger abuses'}, {'id': 45, 'name': 'SNMP'}, {'id': 46, 'name': 'NIS'},
                 {'id': 47, 'name': 'Mandriva Local Security Checks'},
                 {'id': 48, 'name': 'VMware ESX Local Security Checks'}, {'id': 49, 'name': 'Brute force attacks'},
                 {'id': 50, 'name': 'Junos Local Security Checks'},
                 {'id': 51, 'name': 'Scientific Linux Local Security Checks'}, {'id': 52, 'name': 'Mobile Devices'},
                 {'id': 53, 'name': 'Oracle Linux Local Security Checks'},
                 {'id': 54, 'name': 'Amazon Linux Local Security Checks'},
                 {'id': 55, 'name': 'Palo Alto Local Security Checks'},
                 {'id': 56, 'name': 'Huawei Local Security Checks'},
                 {'id': 57, 'name': 'F5 Networks Local Security Checks'},
                 {'id': 58, 'name': 'OracleVM Local Security Checks'}, {'id': 59, 'name': 'Incident Response'},
                 {'id': 60, 'name': 'Virtuozzo Local Security Checks'}], 'type': 'dropdown_multi'},
                                         'readable_name': 'Plugin Family', 'operators': ['eq', 'neq']},
    {'name': 'plugin.id', 'group_name': 'vulnerability', 'control': {'maxlength': 1000,
                                                                     'regex': '^(0|[1-9][0-9]{0,6})(-([1-9][0-9]{0,6}))?(,(0|[1-9][0-9]{0,6})(-([1-9][0-9]{0,6}))?)*$',
                                                                     'readable_regex': 'XXXXX,XXXXX-XXXXX',
                                                                     'type': 'entry'}, 'readable_name': 'Plugin ID',
     'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.plugin_modification_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Plugin Modification Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.name', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Plugin Name',
     'operators': ['eq', 'neq', 'match', 'nmatch']}, {'name': 'output', 'group_name': 'vulnerability',
                                                      'control': {'regex': '.*', 'readable_regex': 'text,other text',
                                                                  'type': 'entry'}, 'readable_name': 'Plugin Output',
                                                      'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.plugin_publication_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Plugin Publication Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.attributes.plugin_type', 'group_name': 'vulnerability',
     'control': {'list': ['local', 'remote'], 'type': 'dropdown'}, 'readable_name': 'Plugin Type',
     'operators': ['eq', 'neq']}, {'name': 'port.port', 'group_name': 'vulnerability', 'control': {'maxlength': 1000,
                                                                                                   'regex': '^[0-9]{1,5}(-[0-9]{1,5})?(,[0-9]{1,5}(-[0-9]{1,5})?)*$',
                                                                                                   'readable_regex': '80,8000-8080',
                                                                                                   'type': 'entry'},
                                   'readable_name': 'Port', 'operators': ['eq', 'neq', 'gte', 'lte']},
    {'name': 'port.protocol', 'group_name': 'vulnerability',
     'control': {'list': ['tcp', 'udp', 'icmp'], 'type': 'dropdown'}, 'readable_name': 'Protocol',
     'operators': ['eq', 'neq']}, {'name': 'modification', 'group_name': 'vulnerability',
                                   'control': {'list': ['Accepted', 'Recasted'], 'type': 'dropdown'},
                                   'readable_name': 'Recast & Accept', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.xref:Secunia', 'group_name': 'vulnerability',
     'control': {'maxlength': 18, 'regex': '^[0-9]+(,[0-9]+)*$', 'readable_regex': 'NUMBER', 'type': 'entry'},
     'readable_name': 'Secunia ID', 'operators': ['eq', 'neq', 'match', 'nmatch']},
    {'name': 'plugin.attributes.see_also', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'See Also',
     'operators': ['eq', 'neq', 'match', 'nmatch']}, {'name': 'severity', 'group_name': 'vulnerability',
                                                      'control': {'list': ['Info', 'Low', 'Medium', 'High', 'Critical'],
                                                                  'type': 'dropdown_multi'},
                                                      'readable_name': 'Severity', 'operators': ['eq', 'neq']},
    {'name': 'plugin.attributes.solution', 'group_name': 'vulnerability',
     'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'}, 'readable_name': 'Solution',
     'operators': ['match', 'nmatch']}, {'name': 'plugin.attributes.synopsis', 'group_name': 'vulnerability',
                                         'control': {'regex': '.*', 'readable_regex': 'TEXT', 'type': 'entry'},
                                         'readable_name': 'Synopsis', 'operators': ['match', 'nmatch']},
    {'name': 'plugin.attributes.unsupported_by_vendor', 'group_name': 'vulnerability',
     'control': {'list': ['true', 'false'], 'type': 'dropdown'}, 'readable_name': 'Unsupported By Vendor',
     'operators': ['eq', 'neq']}, {'name': 'tracking.first_found', 'group_name': 'vulnerability',
                                   'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD',
                                               'type': 'datefield'}, 'readable_name': 'Vulnerability First Seen',
                                   'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'tracking.last_found', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Vulnerability Last Seen',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'plugin.attributes.vuln_publication_date', 'group_name': 'vulnerability',
     'control': {'regex': '^[0-9]{4}/[0-9]{2}/[0-9]{2}$', 'readable_regex': 'YYYY/MM/DD', 'type': 'datefield'},
     'readable_name': 'Vulnerability Publication Date',
     'operators': ['date-lt', 'date-lte', 'date-gt', 'date-gte', 'date-eq', 'date-neq']},
    {'name': 'tracking.state', 'group_name': 'vulnerability',
     'control': {'list': ['New', 'Fixed', 'Active', 'Resurfaced'], 'type': 'dropdown'},
     'readable_name': 'Vulnerability State', 'operators': ['eq', 'neq']}], 'compliance': [], 'comphosts': [],
            'history': [{'uuid': '58c59ba0-22a4-48fb-b602-d50be9ef12ee', 'scheduler': 0, 'creation_date': 1540792945,
                         'owner_id': 2, 'type': 'remote', 'status': 'pending', 'alt_targets_used': False,
                         'last_modification_date': 1540793587, 'history_id': 11423531}],
            'info': {'timestamp': 1540793587, 'control': True, 'hostcount': 1, 'alt_targets_used': False,
                     'status': 'not completed', 'edit_allowed': False, 'user_permissions': 128, 'object_id': 330,
                     'scan_start': 1540792945, 'shared': None, 'no_target': False,
                     'uuid': '58c59ba0-22a4-48fb-b602-d50be9ef12ee', 'name': 'Test', 'scanner_end': None,
                     'scanner_start': None, 'folder_id': None, 'owner': 'kkart@juniper.net', 'scan_type': 'remote',
                     'policy': 'Advanced Network Scan',
                     'schedule_uuid': 'template-e9c66add-fd51-688a-3329-420ef3f7d71ec780579ac958294b',
                     'hasaudittrail': True, 'haskb': True, 'targets': '10.207.147.168', 'acls': [
                    {'id': None, 'display_name': None, 'name': None, 'permissions': 0, 'owner': None,
                     'type': 'default'},
                    {'id': 2, 'display_name': 'kkart@juniper.net', 'name': 'kkart@juniper.net', 'permissions': 128,
                     'owner': 1, 'type': 'user'}], 'scanner_name': 'nessus-va-vm.englab.juniper.net',
                     'scan_end': 1540793587, 'pci-can-upload': False},
            'remediations': {'num_cves': 20, 'num_impacted_hosts': 0, 'num_remediated_cves': 0, 'remediations': [],
                             'num_hosts': 1}, 'vulnerabilities': [
        {'severity': 0, 'vuln_index': 1, 'plugin_id': 11111, 'count': 6, 'plugin_name': 'RPC Services Enumeration',
         'plugin_family': 'Service detection'}, {'severity': 2, 'vuln_index': 2, 'plugin_id': 10068, 'count': 1,
                                                 'plugin_name': 'Finger Service Remote Information Disclosure',
                                                 'plugin_family': 'Misc.'},
        {'severity': 0, 'vuln_index': 3, 'plugin_id': 10092, 'count': 1, 'plugin_name': 'FTP Server Detection',
         'plugin_family': 'Service detection'}, {'severity': 0, 'vuln_index': 4, 'plugin_id': 10223, 'count': 1,
                                                 'plugin_name': 'RPC portmapper Service Detection',
                                                 'plugin_family': 'RPC'},
        {'severity': 4, 'vuln_index': 5, 'plugin_id': 10264, 'count': 1,
         'plugin_name': 'SNMP Agent Default Community Names', 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 6, 'plugin_id': 10267, 'count': 1,
         'plugin_name': 'SSH Server Type and Version Information', 'plugin_family': 'Service detection'},
        {'severity': 0, 'vuln_index': 7, 'plugin_id': 10281, 'count': 1, 'plugin_name': 'Telnet Server Detection',
         'plugin_family': 'Service detection'},
        {'severity': 0, 'vuln_index': 8, 'plugin_id': 10287, 'count': 1, 'plugin_name': 'Traceroute Information',
         'plugin_family': 'General'}, {'severity': 0, 'vuln_index': 9, 'plugin_id': 10551, 'count': 1,
                                       'plugin_name': 'SNMP Request Network Interfaces Enumeration',
                                       'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 10, 'plugin_id': 10800, 'count': 1,
         'plugin_name': 'SNMP Query System Information Disclosure', 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 11, 'plugin_id': 10881, 'count': 1,
         'plugin_name': 'SSH Protocol Versions Supported', 'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 12, 'plugin_id': 10884, 'count': 1,
         'plugin_name': 'Network Time Protocol (NTP) Server Detection', 'plugin_family': 'Service detection'},
        {'severity': 0, 'vuln_index': 13, 'plugin_id': 11936, 'count': 1, 'plugin_name': 'OS Identification',
         'plugin_family': 'General'}, {'severity': 0, 'vuln_index': 14, 'plugin_id': 12053, 'count': 1,
                                       'plugin_name': 'Host Fully Qualified Domain Name (FQDN) Resolution',
                                       'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 15, 'plugin_id': 19506, 'count': 1, 'plugin_name': 'Nessus Scan Information',
         'plugin_family': 'Settings'}, {'severity': 1, 'vuln_index': 16, 'plugin_id': 34324, 'count': 1,
                                        'plugin_name': 'FTP Supports Cleartext Authentication', 'plugin_family': 'FTP'},
        {'severity': 0, 'vuln_index': 17, 'plugin_id': 35296, 'count': 1,
         'plugin_name': 'SNMP Protocol Version Detection', 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 18, 'plugin_id': 35716, 'count': 1,
         'plugin_name': 'Ethernet Card Manufacturer Detection', 'plugin_family': 'Misc.'},
        {'severity': 0, 'vuln_index': 19, 'plugin_id': 39520, 'count': 1,
         'plugin_name': 'Backported Security Patch Detection (SSH)', 'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 20, 'plugin_id': 40448, 'count': 1,
         'plugin_name': 'SNMP Supported Protocols Detection', 'plugin_family': 'SNMP'},
        {'severity': 3, 'vuln_index': 21, 'plugin_id': 41028, 'count': 1,
         'plugin_name': 'SNMP Agent Default Community Name (public)', 'plugin_family': 'SNMP'},
        {'severity': 2, 'vuln_index': 22, 'plugin_id': 42263, 'count': 1, 'plugin_name': 'Unencrypted Telnet Server',
         'plugin_family': 'Misc.'}, {'severity': 0, 'vuln_index': 23, 'plugin_id': 45590, 'count': 1,
                                     'plugin_name': 'Common Platform Enumeration (CPE)', 'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 24, 'plugin_id': 53335, 'count': 1, 'plugin_name': 'RPC portmapper (TCP)',
         'plugin_family': 'RPC'},
        {'severity': 0, 'vuln_index': 25, 'plugin_id': 54615, 'count': 1, 'plugin_name': 'Device Type',
         'plugin_family': 'General'},
        {'severity': 0, 'vuln_index': 26, 'plugin_id': 55932, 'count': 1, 'plugin_name': 'Junos Version Detection',
         'plugin_family': 'Junos Local Security Checks'},
        {'severity': 0, 'vuln_index': 27, 'plugin_id': 70657, 'count': 1,
         'plugin_name': 'SSH Algorithms and Languages Supported', 'plugin_family': 'Misc.'},
        {'severity': 1, 'vuln_index': 28, 'plugin_id': 70658, 'count': 1,
         'plugin_name': 'SSH Server CBC Mode Ciphers Enabled', 'plugin_family': 'Misc.'},
        {'severity': 1, 'vuln_index': 29, 'plugin_id': 71049, 'count': 1,
         'plugin_name': 'SSH Weak MAC Algorithms Enabled', 'plugin_family': 'Misc.'},
        {'severity': 2, 'vuln_index': 30, 'plugin_id': 76474, 'count': 1,
         'plugin_name': "SNMP 'GETBULK' Reflection DDoS", 'plugin_family': 'SNMP'},
        {'severity': 0, 'vuln_index': 31, 'plugin_id': 86420, 'count': 1, 'plugin_name': 'Ethernet MAC Addresses',
         'plugin_family': 'General'}, {'severity': 2, 'vuln_index': 32, 'plugin_id': 90317, 'count': 1,
                                       'plugin_name': 'SSH Weak Algorithms Supported', 'plugin_family': 'Misc.'},
        {'severity': 2, 'vuln_index': 33, 'plugin_id': 97861, 'count': 1,
         'plugin_name': 'Network Time Protocol (NTP) Mode 6 Scanner', 'plugin_family': 'Misc.'},
        {'severity': 0, 'vuln_index': 34, 'plugin_id': 110723, 'count': 1, 'plugin_name': 'No Credentials Provided',
         'plugin_family': 'Settings'}, {'severity': 0, 'vuln_index': 35, 'plugin_id': 117886, 'count': 1,
                                        'plugin_name': 'Local Checks Not Enabled (info)', 'plugin_family': 'Settings'}]}

token = {'token': '8e0a493c718d5143cbbaf8031d61af9040b9a6748f679afc5cbe0fc9ce34ab8e'}
id = {'scan': {'owner_uuid': '99db1f20-5a7d-4435-933a-26fa8aeb2c8f', 'owner_id': 2, 'dashboard_file': None, 'rrules': None, 'last_modification_date': 1540805508, 'include_aggregate': True, 'description': 'Basic Scan using API', 'policy_id': 335, 'timezone': None, 'owner': 'kkart@juniper.net', 'scan_time_window': None, 'default_permissions': 0, 'notification_filters': None, 'scanner_uuid': '8cc585f4-78ca-4ecf-9449-9325ed6d11c2', 'container_id': '0153b20f-bcff-41fd-bb9c-179b2bf11195', 'emails': None, 'type': 'public', 'use_dashboard': False, 'name': 'Test', 'creation_date': 1540805508, 'scanner_id': None, 'id': 336, 'custom_targets': '10.207.148.216', 'starttime': None, 'shared': 0, 'enabled': True, 'uuid': 'template-3f83b0f4-3e20-b4e0-3bf3-50fd89c4fea25804b0803c871e74', 'user_permissions': 128, 'sms': ''}}
ip = "10.207.148.216"

class TestNessus(unittest.TestCase):
    def test_nessus_vulner(self):
        ip_add = "10.207.148.216"
        nessus.get_token = MagicMock()
        nessus.get_token.return_value = "58745b6b1987895a126363d87c8b6f87940077f5c8de3fed4bf5fcddb7bc639d"
        nessus.get_id = MagicMock()
        nessus.get_id.return_value = "256"
        nessus.get_data = MagicMock()
        nessus.get_data.return_value = full_scan
        nessus.check_status = MagicMock()
        nessus.check_status.return_value = "completed"
        nessus.display = MagicMock()
        nessus.display.return_value = full_scan["vulnerabilities"]
        nessus.get_result = MagicMock()
        nessus.get_result.return_value = "PASS"
        result = nessus.nessus_vulner(ip_add)
        self.assertEqual(result, "PASS")

    def test_nessus_vulner1(self):
        ip_add = "10.207.148.216"
        nessus.get_token = MagicMock()
        nessus.get_token.return_value = "58745b6b1987895a126363d87c8b6f87940077f5c8de3fed4bf5fcddb7bc639d"
        nessus.get_id = MagicMock()
        nessus.get_id.return_value = "256"
        nessus.get_data = MagicMock()
        nessus.get_data.return_value = full_scan_neg
        nessus.check_status = MagicMock()
        nessus.check_status.return_value = "not completed"
        nessus.display = MagicMock()
        nessus.display.return_value = full_scan["vulnerabilities"]
        nessus.get_result = MagicMock()
        nessus.get_result.return_value = "FAIL"
        result = nessus.nessus_vulner(ip_add)
        self.assertEqual(result, "FAIL")

    def test_check_status(self):
        result = nessus.check_status(full_scan)

    def test_check_status1(self):
        result = nessus.check_status(full_scan_neg)

    def test_display(self):
        nessus.display(vurl)

    def test_display1(self):
        result = nessus.display(vurl_neg)

    def test_get_result(self):
        result = nessus.get_result(vurl)
        self.assertEqual(result, "PASS")

    def test_get_result1(self):
        result = nessus.get_result(vurl_neg)
        self.assertEqual(result, "FAIL")

if __name__ == '__main__':
    unittest.main()
